UTCAPPCMS.MVC/Controllers/ParkingsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Newtonsoft.Json;
using UTCAPPCMS.DAL.Models;
using UTCAPPCMS.DAL.Repository.Interfaces;
using UTCAPPCMS.MVC.Helpers;
using UTCAPPCMS.MVC.Models;

namespace UTCAPPCMS.MVC.Controllers
{// Session and Privilage is Set
    public class ParkingsController : Controller
    {
        private readonly IUnitOfWork<Parking> _unitOfWork;
        private readonly IUnitOfWork<UserType> _UserTypeunitOfWork;
        private readonly IUnitOfWork<FormPages> _FormPagesunitOfWork;

        private readonly IWebHostEnvironment _iwebHost;
        private readonly IdefaultRepository _idefaultRepository;
        private readonly IUserManagmentRepos _userManagmentRepos;
        private readonly ISystemLogger _Logging;

        private readonly string FormKey = "Parking";
        private readonly string ImgPath = "/Files/Images/";

        public ParkingsController(IUnitOfWork<FormPages> _FormPagesunitOfWork,IUnitOfWork<UserType> _UserTypeunitOfWork,IdefaultRepository _idefaultRepository, IUnitOfWork<Parking> _unitOfWork, ISystemLogger _Logging, IUserManagmentRepos _userManagmentRepos, IWebHostEnvironment _iwebHost)
        {
            this._unitOfWork = _unitOfWork;
            this._iwebHost = _iwebHost;
            this._idefaultRepository = _idefaultRepository;
            this._Logging = _Logging;
            this._userManagmentRepos = _userManagmentRepos;
            this._UserTypeunitOfWork = _UserTypeunitOfWork;
            this._FormPagesunitOfWork = _FormPagesunitOfWork;
        }

        // GET: Parkings
        public async Task<IActionResult> Index()
        {
            var sessionUser = JsonConvert.DeserializeObject<CurrentLoginUser>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserImg = sessionUser.UserImg;
            ViewBag.UserName = sessionUser.UserName;
            var Priv =await _idefaultRepository.GetPrivilage(sessionUser.UserId, FormKey.Trim());
            try
            {
                if (Priv != null)
                {
                    if (Priv.User_View != null && Priv.User_View == true)
                    {
                        var parking = new List<Parking>();
                        if (sessionUser.ParkingId == null || sessionUser.ParkingId == 0)    // Admin Account
                        {
                            parking = await _unitOfWork.Repository.where(x => x.IsDeleted == false && x.IsEnable == true).ToListAsync();
                            
                        }
                        else    // Company Accouint
                        {
                            parking = await _unitOfWork.Repository.where(x => x.IsDeleted == false && x.IsEnable == true && x.Id == sessionUser.ParkingId).ToListAsync();
                        }
                        
                        if (parking != null)
                        {

                            await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "View", "Success Get index View", "");
                            return View(parking);
                        }
                        else
                        {
                            await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "View", "Data NotFound in Table", "");
                            return Redirect("/Home/ClientSideError404");
                        }
                    }
                    else
                    {
                        await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "View", "Not Authorized to View This Page", "");
                        return Redirect("/Home/ClientSideError404");
                    }
                }
                else
                {
                    await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "View", "Privilage Returns Null : User Don't Assign to Privilage Group or Custom Privilage ", "");
                    return Redirect("/Home/ClientSideError404");
                }
            }
            catch (Exception ex)
            {
                await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "View",ex.Message, "");
                return Redirect("/Home/ServerSideError500");
            }    
        }

        public async Task<IActionResult> Create(int? id)
        {
            var sessionUser = JsonConvert.DeserializeObject<CurrentLoginUser>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserImg = sessionUser.UserImg;
            ViewBag.UserName = sessionUser.UserName;
            ViewBag.ID = id;
            var Priv =await _idefaultRepository.GetPrivilage(sessionUser.UserId, FormKey.Trim());
            try
            {
                if (Priv != null)
                {
                    ViewBag.SessionParkingId = sessionUser.ParkingId;
                    if (id != null)// for Edit
                    {
                        ViewBag.IdUpdate = id;
                        if (Priv.User_Edit == true)
                        {
                            if (id == null)
                            {
                                await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Edit", $"Error Null Refrance : Id ({id.Value}) is Equal to null", "");
                                return NotFound();
                            }

                            var parking = await _unitOfWork.Repository.GetById_FindAsync(id.Value);
                            if (parking == null)
                            {
                                await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Edit", $"Error Null Refrance : Parking Id ({id.Value}) is NotFound", "");
                                return NotFound();
                            }
                            var VMEditParking = new EditParkingViewModel
                            {
                                ReferanceKey = parking.ReferanceKey,
                                AddressAr = parking.AddressAr,
                                AddressEn = parking.AddressEn,
                                NameAr = parking.NameAr,
                                NameEn = parking.NameEn,
                                ContactEmail = parking.ContactEmail,
                                ContactName = parking.ContactName,
                                ContactPhone = parking.ContactPhone,
                                CreatedDate = parking.CreatedDate,
                                CreatedUserId = parking.CreatedUserId,
                                Description = parking.Description,
                                IsDeleted = parking.IsDeleted,
                                IsEnable = parking.IsEnable,
                                ModifiedUserId = parking.ModifiedUserId,
                                LastModifiedDate = parking.LastModifiedDate,
                                Id = parking.Id,
                                LogoPath = parking.Logo,
                                InvoiceLogoPath = parking.Invoicelogo,
                                Logo = null,
                                Invoicelogo = null
                            };
                            ViewBag.logo = parking.Logo;
                            ViewBag.inlogo = parking.Invoicelogo;
                            ViewBag.Edit = true;
                            await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Edit", "Success Get Update View", "");
                            return View(VMEditParking);
                        }
                        else
                        {
                            await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Edit", "Not Authorized to View This Page", "");
                            return Redirect("/Home/ClientSideError404");
                        }
                    }
                    else// for Add
                    {
                        if (Priv.User_Add == true)
                        {
                            ViewBag.Edit = false;
                            await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Add", "Success Get Add View", "");
                            return View();
                        }
                        else
                        {
                            await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Add", "Not Authorized to View This Page", "");
                            return Redirect("/Home/ClientSideError404");
                        }
                    }
                }
                else
                {
                    await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Add", "Privilage Returns Null : User Don't Assign to Privilage Group or Custom Privilage ", "");
                    return Redirect("/Home/ClientSideError404");
                }
            }
            catch(Exception ex)
            {
                await _Logging.TraceLogsAsync(sessionUser.UserId, FormKey, "Add", ex.Message, "");
                return Redirect("/Home/ServerSideError500");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? id,IFormFile ifilelogo, IFormFile ifileInvoice, Parking parking)
        {
            var sessionUser = JsonConvert.DeserializeObject<CurrentLoginUser>(HttpContext.Session.GetString("SessionUser"));
            ViewBag.UserImg = sessionUser.UserImg;
            ViewBag.UserName = sessionUser.UserName;
            ViewBag.ID = id;         
            var Priv =await _idefaultRepository.GetPrivilage(sessionUser.UserId, FormKey.Trim());

UTCAPPCMS.MVC/Views/ParkingLocations/Index.cshtml
@model IEnumerable<UTCAPPCMS.DAL.Models.ParkingLocations>

@{
    ViewData["Title"] = "Locations";
    ViewData["shortdesc"] = "manage Parking Locations information";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>


<style>
    #outer {
        float: left;
        width: 1000px;
        overflow: hidden;
        white-space: nowrap;
        display: inline-block;
    }

    #left-button {
        float: left;
        width: 30px;
        text-align: center;
    }

    #right-button {
        float: left;
        width: 30px;
        text-align: center;
    }

    a {
        text-decoration: none;
        font-weight: bolder;
        color: red;
    }

    #inner:first-child {
        margin-left: 0;
    }

    label {
        margin-left: 10px;
    }

    .hide {
        display: none;
    }
</style>


<div class="container">
    <div class="">
        <div class="col-xs-12 col-lg-12">
            <div class="card">
                <div class="card-header">

                    <div class="col-md-12 text-right">
                        <a asp-area="" asp-controller="ParkingLocations" asp-action="Create">
                            <button class="btn btn-danger btn-sm btn-labeled" type="button">
                                <span class="btn-label">
                                    <span class="icon icon-plus icon-lg icon-fw"></span>
                                </span>
                                Add New
                            </button>
                        </a>
                    </div>

                    <a asp-area="" asp-controller="Parkings" asp-action="Excel">
                        <button class="btn btn-danger btn-sm btn-labeled" type="button">
                            <span class="btn-label">
                                <span class="icon icon-download icon-lg icon-fw"></span>
                            </span>
                            Download Excel
                        </button>
                    </a>

                </div>
                <div class="card-body">

                    <div id="elem">
                        <table id="demo-datatables-buttons-1" class="table table-striped table-hover table-nowrap dataTable" cellspacing="0" width="100%">

                            <thead>
                                <tr>
                                    <th> # </th>
                                    <th> Site Name </th>
                                    <th> Site Number </th>
                                    <th> Contact Name </th>
                                    <th> Contact Email </th>
                                    <th> Contact Phone </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int i = 0;}
                                @foreach (var item in Model)
                                {
                                    i++;
                                    <tr>
                                        <td> @i </td>
                                        <td> @Html.DisplayFor(modelItem => item.SiteName) </td>
                                        <td> @Html.DisplayFor(modelItem => item.SiteNo) </td>
                                        <td> @Html.DisplayFor(modelItem => item.ContactName) </td>
                                        <td> @Html.DisplayFor(modelItem => item.ContactEmail) </td>
                                        <td> @Html.DisplayFor(modelItem => item.ContactPhone) </td>
                                        <td>
                                            <div class="btn-group dropdown">
                                                <button class="btn btn-danger" type="button">Actions</button>
                                                <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown" type="button">
                                                    <span class="caret"></span>
                                                    <span class="sr-only">Toggle Dropdown</span>
                                                </button>
                                                <ul class="dropdown-menu">
                                                    <li> <a asp-action="Create" asp-route-id="@item.Id">Edit</a> </li>
                                                    <li> <a data-toggle="modal" data-target="#@("a"+item.Id)">Delete</a> </li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
    @foreach (var item in Model)
    {
        <Text>

        $("#@item.Id").click(function () {


                    //console.log('Form is submitting');
                    $.ajax({
                        url: "/ParkingLocations/DeleteConfirmed",
                data: { id: @item.Id },
                type: "post"
                        ,
                        success: window.location.replace("/ParkingLocations/Index")
            })



            });

    </Text>
    }
    })
</script>

<script>
    /* $(function () {
         var print = function (msg) {
             alert(msg);
         };

         var setInvisible = function (elem) {
             elem.css('visibility', 'hidden');
         };
         var setVisible = function (elem) {
             elem.css('visibility', 'visible');
         };

         var elem = $("#elem");
         var items = elem.children();

         // Inserting Buttons
         elem.prepend('<div id="right-button" style="visibility: hidden;"><a href="#"><</a></div>');
         elem.append('  <div id="left-button"><a href="#">></a></div>');

         // Inserting Inner
         items.wrapAll('<div id="inner" />');

         // Inserting Outer
         debugger;
         elem.find('#inner').wrap('<div id="outer"/>');

         var outer = $('#outer');

         var updateUI = function () {
             var maxWidth = outer.outerWidth(true);
             var actualWidth = 0;
             $.each($('#inner >'), function (i, item) {
                 actualWidth += $(item).outerWidth(true);
             });

             if (actualWidth <= maxWidth) {
                 setVisible($('#left-button'));
             }
         };
         updateUI();



         $('#right-button').click(function () {
             var leftPos = outer.scrollLeft();
             outer.animate({
                 scrollLeft: leftPos - 200
             }, 800, function () {
                 debugger;
                 if ($('#outer').scrollLeft() <= 0) {
                     setInvisible($('#right-button'));
                 }
             });
         });

         $('#left-button').click(function () {
             setVisible($('#right-button'));
             var leftPos = outer.scrollLeft();
             outer.animate({
                 scrollLeft: leftPos + 200
             }, 800);
         });

         $(window).resize(function () {
             updateUI();
         });
     });
     */
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script src="~/JS/DeleteScripts/ParkingDelete.js"></script>